# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters

trigger:
- main

variables:
  MKL_NUM_THREADS: 1
  NUMEXPR_NUM_THREADS: 1
  OMP_NUM_THREADS: 1
  VML_NUM_THREADS: 1
  OPENBLAS_NUM_THREADS: 1
  JUPYTER_PLATFORM_DIRS: 1
  PYTHONHASHSEED: 12345678 # Ensure tests are correctly gathered by xdist
  TEST_INSTALL: false
  MPLBACKEND: agg
  PYTEST_PATTERN: "(not slow)"
  coverage: true
  test.install: false
  pip.pre: false

jobs:
- template: ci/azure/azure_template_posix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest

- template: ci/azure/azure_template_windows.yml
  parameters:
    name: Windows
    vmImage: windows-latest
